export const ADD_CONTACTS_SUCCESS = 'ADD_CONTACTS_SUCCESS';
export const ADD_CONTACTS_ERROR = 'ADD_CONTACTS_ERROR';

export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_ERROR = 'GET_CONTACTS_ERROR';

export const CHANGE_CONTACT_SUCCESS = 'CHANGE_CONTACT_SUCCESS';
export const CHANGE_CONTACT_ERROR = 'CHANGE_CONTACT_ERROR';